import sys
import os
import json
from typing import Dict, Any, List

from dotenv import load_dotenv

load_dotenv()

sys.path.append(os.path.abspath(os.path.join(os.getcwd(), "..")))


seller_data = [
    {
        "User ID": "seller_0001",
        "Username": "ejones",
        "Location": "Texas, USA",
        "Model": "Antminer S19 XP",
        "Hashrate (TH\/s)": 149,
        "Power (W)": 3557,
        "Estimated Total Daily Rental Price ($)": 6.56,
        "Estimated Hourly Rental Price ($)": 0.27,
        "Quantity Available": 9,
        "Hostname": "asic-node-0.example.com",
        "Port": 22,
        "Password": "!PMgD2jD*p^7",
        "IP Address": "61.22.198.73:4519",
    },
    {
        "User ID": "seller_0002",
        "Username": "staceymurphy",
        "Location": "Oregon, USA",
        "Model": "Antminer S19j Pro+",
        "Hashrate (TH\/s)": 179,
        "Power (W)": 3854,
        "Estimated Total Daily Rental Price ($)": 7.7,
        "Estimated Hourly Rental Price ($)": 0.32,
        "Quantity Available": 2,
        "Hostname": "asic-node-1.example.com",
        "Port": 22,
        "Password": "&jdO(vWad4xn",
        "IP Address": "39.191.219.131:4202",
    },
    {
        "User ID": "seller_0003",
        "Username": "cbrown",
        "Location": "Texas, USA",
        "Model": "WhatsMiner M50S++",
        "Hashrate (TH\/s)": 125,
        "Power (W)": 2807,
        "Estimated Total Daily Rental Price ($)": 5.38,
        "Estimated Hourly Rental Price ($)": 0.22,
        "Quantity Available": 13,
        "Hostname": "asic-node-2.example.com",
        "Port": 22,
        "Password": "!aYm@a!DV1_q",
        "IP Address": "166.139.117.143:9999",
    },
    {
        "User ID": "seller_0004",
        "Username": "kingmary",
        "Location": "North Dakota, USA",
        "Model": "Antminer T21",
        "Hashrate (TH\/s)": 132,
        "Power (W)": 3731,
        "Estimated Total Daily Rental Price ($)": 5.68,
        "Estimated Hourly Rental Price ($)": 0.24,
        "Quantity Available": 6,
        "Hostname": "asic-node-3.example.com",
        "Port": 22,
        "Password": ")K0IDHv$n3rx",
        "IP Address": "45.147.39.191:3200",
    },
    {
        "User ID": "seller_0005",
        "Username": "michelle71",
        "Location": "North Dakota, USA",
        "Model": "WhatsMiner M60S",
        "Hashrate (TH\/s)": 152,
        "Power (W)": 4834,
        "Estimated Total Daily Rental Price ($)": 7.14,
        "Estimated Hourly Rental Price ($)": 0.3,
        "Quantity Available": 14,
        "Hostname": "asic-node-4.example.com",
        "Port": 22,
        "Password": "8UHFFDhw@jd&",
        "IP Address": "131.88.113.6:3621",
    },
    {
        "User ID": "seller_0006",
        "Username": "heatherroberts",
        "Location": "Texas, USA",
        "Model": "Antminer S19k Pro",
        "Hashrate (TH\/s)": 164,
        "Power (W)": 3881,
        "Estimated Total Daily Rental Price ($)": 7.71,
        "Estimated Hourly Rental Price ($)": 0.32,
        "Quantity Available": 2,
        "Hostname": "asic-node-5.example.com",
        "Port": 22,
        "Password": "$8aE%Li1206&",
        "IP Address": "220.242.196.171:8673",
    },
    {
        "User ID": "seller_0007",
        "Username": "matthew76",
        "Location": "Tokyo, Japan",
        "Model": "AvalonMiner 1266",
        "Hashrate (TH\/s)": 194,
        "Power (W)": 6134,
        "Estimated Total Daily Rental Price ($)": 8.54,
        "Estimated Hourly Rental Price ($)": 0.36,
        "Quantity Available": 2,
        "Hostname": "asic-node-6.example.com",
        "Port": 22,
        "Password": "^@wFN2vN)0R&",
        "IP Address": "92.5.106.136:8237",
    },
    {
        "User ID": "seller_0008",
        "Username": "vguzman",
        "Location": "North Dakota, USA",
        "Model": "WhatsMiner M30S++",
        "Hashrate (TH\/s)": 166,
        "Power (W)": 4827,
        "Estimated Total Daily Rental Price ($)": 7.97,
        "Estimated Hourly Rental Price ($)": 0.33,
        "Quantity Available": 2,
        "Hostname": "asic-node-7.example.com",
        "Port": 22,
        "Password": "8sQgKk)@@4!k",
        "IP Address": "124.168.29.232:5453",
    },
    {
        "User ID": "seller_0009",
        "Username": "sharpsamantha",
        "Location": "Oregon, USA",
        "Model": "Antminer S19a Pro",
        "Hashrate (TH\/s)": 211,
        "Power (W)": 5583,
        "Estimated Total Daily Rental Price ($)": 9.49,
        "Estimated Hourly Rental Price ($)": 0.4,
        "Quantity Available": 12,
        "Hostname": "asic-node-8.example.com",
        "Port": 22,
        "Password": "QE#RHO3o#f6u",
        "IP Address": "165.14.68.191:9234",
    },
    {
        "User ID": "seller_0010",
        "Username": "vdavis",
        "Location": "Ohio, USA",
        "Model": "Antminer T19",
        "Hashrate (TH\/s)": 170,
        "Power (W)": 4577,
        "Estimated Total Daily Rental Price ($)": 7.65,
        "Estimated Hourly Rental Price ($)": 0.32,
        "Quantity Available": 6,
        "Hostname": "asic-node-9.example.com",
        "Port": 22,
        "Password": "_LYvNAwQ9pM9",
        "IP Address": "20.131.82.239:9171",
    },
    {
        "User ID": "seller_0011",
        "Username": "shawnmurphy",
        "Location": "Nevada, USA",
        "Model": "WhatsMiner M50",
        "Hashrate (TH\/s)": 100,
        "Power (W)": 2592,
        "Estimated Total Daily Rental Price ($)": 4.5,
        "Estimated Hourly Rental Price ($)": 0.19,
        "Quantity Available": 4,
        "Hostname": "asic-node-10.example.com",
        "Port": 22,
        "Password": "#BWMxldD3FT7",
        "IP Address": "209.142.104.74:3786",
    },
    {
        "User ID": "seller_0012",
        "Username": "kevin47",
        "Location": "New York, USA",
        "Model": "Antminer S17+",
        "Hashrate (TH\/s)": 128,
        "Power (W)": 3671,
        "Estimated Total Daily Rental Price ($)": 5.89,
        "Estimated Hourly Rental Price ($)": 0.25,
        "Quantity Available": 3,
        "Hostname": "asic-node-11.example.com",
        "Port": 22,
        "Password": "^1p1c4cS(YGY",
        "IP Address": "144.109.159.154:6830",
    },
    {
        "User ID": "seller_0013",
        "Username": "daniel11",
        "Location": "Ohio, USA",
        "Model": "WhatsMiner M31S+",
        "Hashrate (TH\/s)": 184,
        "Power (W)": 5660,
        "Estimated Total Daily Rental Price ($)": 8.28,
        "Estimated Hourly Rental Price ($)": 0.34,
        "Quantity Available": 9,
        "Hostname": "asic-node-12.example.com",
        "Port": 22,
        "Password": "g*W3CnDBHe%$",
        "IP Address": "178.12.68.105:5358",
    },
    {
        "User ID": "seller_0014",
        "Username": "ybryant",
        "Location": "Texas, USA",
        "Model": "AvalonMiner 1246",
        "Hashrate (TH\/s)": 123,
        "Power (W)": 3081,
        "Estimated Total Daily Rental Price ($)": 5.78,
        "Estimated Hourly Rental Price ($)": 0.24,
        "Quantity Available": 4,
        "Hostname": "asic-node-13.example.com",
        "Port": 22,
        "Password": "VzAXwj9)#7iS",
        "IP Address": "187.94.120.65:2547",
    },
    {
        "User ID": "seller_0015",
        "Username": "kelly33",
        "Location": "California, USA",
        "Model": "Antminer S19 Pro Hydro",
        "Hashrate (TH\/s)": 185,
        "Power (W)": 4773,
        "Estimated Total Daily Rental Price ($)": 7.95,
        "Estimated Hourly Rental Price ($)": 0.33,
        "Quantity Available": 10,
        "Hostname": "asic-node-14.example.com",
        "Port": 22,
        "Password": "yVOJ5GA377w!",
        "IP Address": "187.61.238.41:2177",
    },
    {
        "User ID": "seller_0016",
        "Username": "mooreangela",
        "Location": "Texas, USA",
        "Model": "WhatsMiner M33S++",
        "Hashrate (TH\/s)": 111,
        "Power (W)": 3037,
        "Estimated Total Daily Rental Price ($)": 5.11,
        "Estimated Hourly Rental Price ($)": 0.21,
        "Quantity Available": 10,
        "Hostname": "asic-node-15.example.com",
        "Port": 22,
        "Password": "&@vbB5GpV_3^",
        "IP Address": "96.119.102.191:3876",
    },
    {
        "User ID": "seller_0017",
        "Username": "ksantiago",
        "Location": "California, USA",
        "Model": "Antminer S21",
        "Hashrate (TH\/s)": 212,
        "Power (W)": 6721,
        "Estimated Total Daily Rental Price ($)": 8.9,
        "Estimated Hourly Rental Price ($)": 0.37,
        "Quantity Available": 10,
        "Hostname": "asic-node-16.example.com",
        "Port": 22,
        "Password": "Chk6S@Znmu&*",
        "IP Address": "147.50.18.175:6876",
    },
    {
        "User ID": "seller_0018",
        "Username": "brian65",
        "Location": "North Dakota, USA",
        "Model": "WhatsMiner M63",
        "Hashrate (TH\/s)": 91,
        "Power (W)": 2034,
        "Estimated Total Daily Rental Price ($)": 3.82,
        "Estimated Hourly Rental Price ($)": 0.16,
        "Quantity Available": 5,
        "Hostname": "asic-node-17.example.com",
        "Port": 22,
        "Password": "!DFIahk11w3Q",
        "IP Address": "196.110.223.16:4922",
    },
    {
        "User ID": "seller_0019",
        "Username": "james41",
        "Location": "New York, USA",
        "Model": "AvalonMiner 1166 Pro",
        "Hashrate (TH\/s)": 173,
        "Power (W)": 3729,
        "Estimated Total Daily Rental Price ($)": 8.13,
        "Estimated Hourly Rental Price ($)": 0.34,
        "Quantity Available": 13,
        "Hostname": "asic-node-18.example.com",
        "Port": 22,
        "Password": "%bQ8Ghx8cGH#",
        "IP Address": "155.163.65.12:8593",
    },
    {
        "User ID": "seller_0020",
        "Username": "vbrown",
        "Location": "Frankfurt, Germany",
        "Model": "Antminer S19e XP",
        "Hashrate (TH\/s)": 177,
        "Power (W)": 5491,
        "Estimated Total Daily Rental Price ($)": 8.32,
        "Estimated Hourly Rental Price ($)": 0.35,
        "Quantity Available": 16,
        "Hostname": "asic-node-19.example.com",
        "Port": 22,
        "Password": "+uhYGkjU*@4J",
        "IP Address": "205.98.85.227:7856",
    },
    {
        "User ID": "seller_0021",
        "Username": "jamestamara",
        "Location": "Texas, USA",
        "Model": "WhatsMiner M63",
        "Hashrate (TH\/s)": 91,
        "Power (W)": 2034,
        "Estimated Total Daily Rental Price ($)": 3.82,
        "Estimated Hourly Rental Price ($)": 0.16,
        "Quantity Available": 15,
        "Hostname": "asic-node-20.example.com",
        "Port": 22,
        "Password": "@1*Mja3lNxn_",
        "IP Address": "199.142.213.8:1490",
    },
    {
        "User ID": "seller_0022",
        "Username": "pnichols",
        "Location": "New York, USA",
        "Model": "WhatsMiner M33S++",
        "Hashrate (TH\/s)": 111,
        "Power (W)": 3037,
        "Estimated Total Daily Rental Price ($)": 5.11,
        "Estimated Hourly Rental Price ($)": 0.21,
        "Quantity Available": 12,
        "Hostname": "asic-node-21.example.com",
        "Port": 22,
        "Password": "f_w^iw6696J8",
        "IP Address": "46.252.104.177:3935",
    },
    {
        "User ID": "seller_0023",
        "Username": "smithkevin",
        "Location": "North Dakota, USA",
        "Model": "Antminer S19 Pro Hydro",
        "Hashrate (TH\/s)": 185,
        "Power (W)": 4773,
        "Estimated Total Daily Rental Price ($)": 7.95,
        "Estimated Hourly Rental Price ($)": 0.33,
        "Quantity Available": 18,
        "Hostname": "asic-node-22.example.com",
        "Port": 22,
        "Password": "$2Zrd28@flXe",
        "IP Address": "212.213.1.40:7874",
    },
    {
        "User ID": "seller_0024",
        "Username": "barnesdavid",
        "Location": "Texas, USA",
        "Model": "AvalonMiner 1266",
        "Hashrate (TH\/s)": 194,
        "Power (W)": 6134,
        "Estimated Total Daily Rental Price ($)": 8.54,
        "Estimated Hourly Rental Price ($)": 0.36,
        "Quantity Available": 10,
        "Hostname": "asic-node-23.example.com",
        "Port": 22,
        "Password": "Bi&fl3WzC)a8",
        "IP Address": "68.14.125.36:8485",
    },
    {
        "User ID": "seller_0025",
        "Username": "anthonythomas",
        "Location": "North Dakota, USA",
        "Model": "WhatsMiner M33S++",
        "Hashrate (TH\/s)": 111,
        "Power (W)": 3037,
        "Estimated Total Daily Rental Price ($)": 5.11,
        "Estimated Hourly Rental Price ($)": 0.21,
        "Quantity Available": 17,
        "Hostname": "asic-node-24.example.com",
        "Port": 22,
        "Password": "*u3bW^rf@1aF",
        "IP Address": "200.237.132.36:8726",
    },
    {
        "User ID": "seller_0026",
        "Username": "jeffrey72",
        "Location": "Georgia, USA",
        "Model": "Antminer S19a Pro",
        "Hashrate (TH\/s)": 211,
        "Power (W)": 5583,
        "Estimated Total Daily Rental Price ($)": 9.49,
        "Estimated Hourly Rental Price ($)": 0.4,
        "Quantity Available": 2,
        "Hostname": "asic-node-25.example.com",
        "Port": 22,
        "Password": "^9SGVM72iqA8",
        "IP Address": "192.96.117.214:4580",
    },
    {
        "User ID": "seller_0027",
        "Username": "hillkimberly",
        "Location": "Texas, USA",
        "Model": "WhatsMiner M33S++",
        "Hashrate (TH\/s)": 111,
        "Power (W)": 3037,
        "Estimated Total Daily Rental Price ($)": 5.11,
        "Estimated Hourly Rental Price ($)": 0.21,
        "Quantity Available": 15,
        "Hostname": "asic-node-26.example.com",
        "Port": 22,
        "Password": "&VpTmNu$2a#D",
        "IP Address": "6.204.118.165:1629",
    },
    {
        "User ID": "seller_0028",
        "Username": "jameslaurie",
        "Location": "Alberta, Canada",
        "Model": "Antminer S17+",
        "Hashrate (TH\/s)": 128,
        "Power (W)": 3671,
        "Estimated Total Daily Rental Price ($)": 5.89,
        "Estimated Hourly Rental Price ($)": 0.25,
        "Quantity Available": 14,
        "Hostname": "asic-node-27.example.com",
        "Port": 22,
        "Password": ")uIhAWoJ@7QR",
        "IP Address": "41.184.116.40:8027",
    },
    {
        "User ID": "seller_0029",
        "Username": "carol51",
        "Location": "Oregon, USA",
        "Model": "Antminer S19e XP",
        "Hashrate (TH\/s)": 177,
        "Power (W)": 5491,
        "Estimated Total Daily Rental Price ($)": 8.32,
        "Estimated Hourly Rental Price ($)": 0.35,
        "Quantity Available": 20,
        "Hostname": "asic-node-28.example.com",
        "Port": 22,
        "Password": "V9Xin5gw*3M8",
        "IP Address": "149.181.113.117:2895",
    },
    {
        "User ID": "seller_0030",
        "Username": "joshuapotter",
        "Location": "Nevada, USA",
        "Model": "Antminer S19e XP",
        "Hashrate (TH\/s)": 177,
        "Power (W)": 5491,
        "Estimated Total Daily Rental Price ($)": 8.32,
        "Estimated Hourly Rental Price ($)": 0.35,
        "Quantity Available": 15,
        "Hostname": "asic-node-29.example.com",
        "Port": 22,
        "Password": "@#3LqToq0u)X",
        "IP Address": "85.194.185.177:4906",
    },
    {
        "User ID": "seller_0031",
        "Username": "samuel13",
        "Location": "Seoul, South Korea",
        "Model": "Antminer T19",
        "Hashrate (TH\/s)": 170,
        "Power (W)": 4577,
        "Estimated Total Daily Rental Price ($)": 7.65,
        "Estimated Hourly Rental Price ($)": 0.32,
        "Quantity Available": 14,
        "Hostname": "asic-node-30.example.com",
        "Port": 22,
        "Password": "u!bHIknP#R7x",
        "IP Address": "74.139.135.67:4891",
    },
    {
        "User ID": "seller_0032",
        "Username": "shaneberg",
        "Location": "Oregon, USA",
        "Model": "Antminer T21",
        "Hashrate (TH\/s)": 132,
        "Power (W)": 3731,
        "Estimated Total Daily Rental Price ($)": 5.68,
        "Estimated Hourly Rental Price ($)": 0.24,
        "Quantity Available": 9,
        "Hostname": "asic-node-31.example.com",
        "Port": 22,
        "Password": "f#9QyMVxJ@yE",
        "IP Address": "116.116.49.244:5297",
    },
    {
        "User ID": "seller_0033",
        "Username": "lwilliams",
        "Location": "North Dakota, USA",
        "Model": "Antminer S19 Pro Hydro",
        "Hashrate (TH\/s)": 185,
        "Power (W)": 4773,
        "Estimated Total Daily Rental Price ($)": 7.95,
        "Estimated Hourly Rental Price ($)": 0.33,
        "Quantity Available": 2,
        "Hostname": "asic-node-32.example.com",
        "Port": 22,
        "Password": "zH%5*LqHU%Vo",
        "IP Address": "193.137.4.253:4079",
    },
    {
        "User ID": "seller_0034",
        "Username": "sarahholmes",
        "Location": "California, USA",
        "Model": "Antminer S19 XP",
        "Hashrate (TH\/s)": 149,
        "Power (W)": 3557,
        "Estimated Total Daily Rental Price ($)": 6.56,
        "Estimated Hourly Rental Price ($)": 0.27,
        "Quantity Available": 5,
        "Hostname": "asic-node-33.example.com",
        "Port": 22,
        "Password": "ru8mhUSbXz)T",
        "IP Address": "193.40.104.184:8837",
    },
    {
        "User ID": "seller_0035",
        "Username": "wallamber",
        "Location": "Texas, USA",
        "Model": "WhatsMiner M33S++",
        "Hashrate (TH\/s)": 111,
        "Power (W)": 3037,
        "Estimated Total Daily Rental Price ($)": 5.11,
        "Estimated Hourly Rental Price ($)": 0.21,
        "Quantity Available": 3,
        "Hostname": "asic-node-34.example.com",
        "Port": 22,
        "Password": "cZSoxPJb*4Ap",
        "IP Address": "153.215.220.1:8185",
    },
    {
        "User ID": "seller_0036",
        "Username": "lhuff",
        "Location": "Ohio, USA",
        "Model": "WhatsMiner M30S++",
        "Hashrate (TH\/s)": 166,
        "Power (W)": 4827,
        "Estimated Total Daily Rental Price ($)": 7.97,
        "Estimated Hourly Rental Price ($)": 0.33,
        "Quantity Available": 6,
        "Hostname": "asic-node-35.example.com",
        "Port": 22,
        "Password": "z$mml6UwWR(u",
        "IP Address": "166.138.36.164:4589",
    },
    {
        "User ID": "seller_0037",
        "Username": "nroman",
        "Location": "New York, USA",
        "Model": "WhatsMiner M33S++",
        "Hashrate (TH\/s)": 111,
        "Power (W)": 3037,
        "Estimated Total Daily Rental Price ($)": 5.11,
        "Estimated Hourly Rental Price ($)": 0.21,
        "Quantity Available": 5,
        "Hostname": "asic-node-36.example.com",
        "Port": 22,
        "Password": "#8QBtkLH4aNR",
        "IP Address": "66.155.126.246:6176",
    },
    {
        "User ID": "seller_0038",
        "Username": "kgallegos",
        "Location": "California, USA",
        "Model": "WhatsMiner M50",
        "Hashrate (TH\/s)": 100,
        "Power (W)": 2592,
        "Estimated Total Daily Rental Price ($)": 4.5,
        "Estimated Hourly Rental Price ($)": 0.19,
        "Quantity Available": 1,
        "Hostname": "asic-node-37.example.com",
        "Port": 22,
        "Password": "@MDdPRL&s9$p",
        "IP Address": "137.108.171.173:8715",
    },
    {
        "User ID": "seller_0039",
        "Username": "laneruth",
        "Location": "New York, USA",
        "Model": "Antminer S19 Pro Hydro",
        "Hashrate (TH\/s)": 185,
        "Power (W)": 4773,
        "Estimated Total Daily Rental Price ($)": 7.95,
        "Estimated Hourly Rental Price ($)": 0.33,
        "Quantity Available": 10,
        "Hostname": "asic-node-38.example.com",
        "Port": 22,
        "Password": "((69ISxpbNKm",
        "IP Address": "209.93.255.151:6493",
    },
    {
        "User ID": "seller_0040",
        "Username": "djenkins",
        "Location": "Stockholm, Sweden",
        "Model": "WhatsMiner M30S++",
        "Hashrate (TH\/s)": 166,
        "Power (W)": 4827,
        "Estimated Total Daily Rental Price ($)": 7.97,
        "Estimated Hourly Rental Price ($)": 0.33,
        "Quantity Available": 18,
        "Hostname": "asic-node-39.example.com",
        "Port": 22,
        "Password": "RjJlh1Vk&03$",
        "IP Address": "212.231.82.207:1594",
    },
    {
        "User ID": "seller_0041",
        "Username": "rmooney",
        "Location": "Sao Paulo, Brazil",
        "Model": "AvalonMiner 1246",
        "Hashrate (TH\/s)": 123,
        "Power (W)": 3081,
        "Estimated Total Daily Rental Price ($)": 5.78,
        "Estimated Hourly Rental Price ($)": 0.24,
        "Quantity Available": 3,
        "Hostname": "asic-node-40.example.com",
        "Port": 22,
        "Password": "zULK7OXmD3u!",
        "IP Address": "108.143.35.216:5154",
    },
    {
        "User ID": "seller_0042",
        "Username": "mercedes14",
        "Location": "Oregon, USA",
        "Model": "Antminer T19",
        "Hashrate (TH\/s)": 170,
        "Power (W)": 4577,
        "Estimated Total Daily Rental Price ($)": 7.65,
        "Estimated Hourly Rental Price ($)": 0.32,
        "Quantity Available": 4,
        "Hostname": "asic-node-41.example.com",
        "Port": 22,
        "Password": "%9ELY+pZled2",
        "IP Address": "179.30.158.26:3007",
    },
    {
        "User ID": "seller_0043",
        "Username": "dstewart",
        "Location": "New York, USA",
        "Model": "WhatsMiner M33S++",
        "Hashrate (TH\/s)": 111,
        "Power (W)": 3037,
        "Estimated Total Daily Rental Price ($)": 5.11,
        "Estimated Hourly Rental Price ($)": 0.21,
        "Quantity Available": 13,
        "Hostname": "asic-node-42.example.com",
        "Port": 22,
        "Password": "3G1yqDmpL*%e",
        "IP Address": "6.154.63.139:5857",
    },
    {
        "User ID": "seller_0044",
        "Username": "bwilson",
        "Location": "Georgia, USA",
        "Model": "Antminer S19 Pro Hydro",
        "Hashrate (TH\/s)": 185,
        "Power (W)": 4773,
        "Estimated Total Daily Rental Price ($)": 7.95,
        "Estimated Hourly Rental Price ($)": 0.33,
        "Quantity Available": 19,
        "Hostname": "asic-node-43.example.com",
        "Port": 22,
        "Password": "$^3c17UaKfE0",
        "IP Address": "185.162.83.106:9580",
    },
    {
        "User ID": "seller_0045",
        "Username": "alisonhernandez",
        "Location": "California, USA",
        "Model": "WhatsMiner M30S++",
        "Hashrate (TH\/s)": 166,
        "Power (W)": 4827,
        "Estimated Total Daily Rental Price ($)": 7.97,
        "Estimated Hourly Rental Price ($)": 0.33,
        "Quantity Available": 17,
        "Hostname": "asic-node-44.example.com",
        "Port": 22,
        "Password": "&!taPs^16L*2",
        "IP Address": "171.133.209.77:6474",
    },
    {
        "User ID": "seller_0046",
        "Username": "sheliamoss",
        "Location": "North Dakota, USA",
        "Model": "Antminer S17+",
        "Hashrate (TH\/s)": 128,
        "Power (W)": 3671,
        "Estimated Total Daily Rental Price ($)": 5.89,
        "Estimated Hourly Rental Price ($)": 0.25,
        "Quantity Available": 10,
        "Hostname": "asic-node-45.example.com",
        "Port": 22,
        "Password": "Yd086N^t$0aa",
        "IP Address": "223.142.30.126:6895",
    },
    {
        "User ID": "seller_0047",
        "Username": "jamescarr",
        "Location": "Georgia, USA",
        "Model": "WhatsMiner M63",
        "Hashrate (TH\/s)": 91,
        "Power (W)": 2034,
        "Estimated Total Daily Rental Price ($)": 3.82,
        "Estimated Hourly Rental Price ($)": 0.16,
        "Quantity Available": 11,
        "Hostname": "asic-node-46.example.com",
        "Port": 22,
        "Password": ")xM)8Ikrj4dR",
        "IP Address": "171.60.108.252:1659",
    },
    {
        "User ID": "seller_0048",
        "Username": "yjones",
        "Location": "Texas, USA",
        "Model": "WhatsMiner M31S+",
        "Hashrate (TH\/s)": 184,
        "Power (W)": 5660,
        "Estimated Total Daily Rental Price ($)": 8.28,
        "Estimated Hourly Rental Price ($)": 0.34,
        "Quantity Available": 11,
        "Hostname": "asic-node-47.example.com",
        "Port": 22,
        "Password": "bqN&D6a%X^E5",
        "IP Address": "156.253.34.198:7479",
    },
    {
        "User ID": "seller_0049",
        "Username": "klandry",
        "Location": "Nevada, USA",
        "Model": "Antminer S19 Pro Hydro",
        "Hashrate (TH\/s)": 185,
        "Power (W)": 4773,
        "Estimated Total Daily Rental Price ($)": 7.95,
        "Estimated Hourly Rental Price ($)": 0.33,
        "Quantity Available": 9,
        "Hostname": "asic-node-48.example.com",
        "Port": 22,
        "Password": "%(y19NWw1V$$",
        "IP Address": "172.141.4.111:1307",
    },
    {
        "User ID": "seller_0050",
        "Username": "tmarquez",
        "Location": "New York, USA",
        "Model": "WhatsMiner M33S++",
        "Hashrate (TH\/s)": 111,
        "Power (W)": 3037,
        "Estimated Total Daily Rental Price ($)": 5.11,
        "Estimated Hourly Rental Price ($)": 0.21,
        "Quantity Available": 18,
        "Hostname": "asic-node-49.example.com",
        "Port": 22,
        "Password": "D@r8yoYh(uUS",
        "IP Address": "194.139.233.150:4407",
    },
]


class sellerTool:
    def __init__(self, json_path: str):
        self.json_path = json_path
        self._cached_data = None
        self._cache_timestamp = None

    def retrieve(self) -> Dict[str, List[Dict[str, Any]]]:
        """
        Retrieve the candidate data from the JSON file with caching.
        """
        # if not os.path.exists(self.json_path):
        #     raise FileNotFoundError(f"File not found: {self.json_path}")

        # Check if we have cached data and file hasn't been modified
        # current_timestamp = os.path.getmtime(self.json_path)
        # if self._cached_data is not None and self._cache_timestamp == current_timestamp:
        #     return {"Retrieved Data": self._cached_data}

        try:
            # with open(self.json_path, "r") as f:
            #     data = json.load(f)

            # # Cache the data and timestamp
            # self._cached_data = data
            # self._cache_timestamp = current_timestamp

            return {"Retrieved Data": seller_data}
        except Exception as e:
            return {"error": str(e)}


# if __name__ == "__main__":
#     json_file_path = os.path.join("../Data", "seller_data.json")
#     # retriever = RetrieveJSON(json_file_path)
#     # result = retriever.retrieve()
#     print(result)
